[package]
name = "adb-smart-backup"
version = "0.2.0"
edition = "2024"
license = "MIT"
readme = "README.md"
repository = "https://github.com/mohalmah/myphone-backup"

[dependencies]
anyhow = "1"
arabic_reshaper = "0.4"
chrono = { version = "0.4", features = ["serde"] }
eframe = { version = "0.31", default-features = true }
fs2 = "0.4"
rfd = "0.15"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
unicode-bidi = "0.3"
